language: python
python:
 - "2.6"
 - "2.7"
env:
 - CYTHON_INSTALL="pip install -q cython"
 - CYTHON_INSTALL=""
install:
 - $CYTHON_INSTALL

script:
 - python setup.py build_ext --inplace
 - nosetests

